server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:econext_auth_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:${MYSQL_USER:root}}
    password: ${DB_PASSWORD:${MYSQL_PASSWORD:shivaJ@123}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secret: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:86400000} # 24 hours
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 days

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.econext.auth: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
