# Generated by Django 5.1.6 on 2026-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_auto_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_whitelisted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_whitelisted'], name='products_pr_is_whit_7b6134_idx'),
        ),
    ]
