# Generated by Django 5.1.6 on 2026-10-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_whitelisted_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition_required',
            field=models.TextField(default='Unused, original tags intact, original packaging required'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.TextField(default='7-day replacement or return'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_window_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_m3',
            field=models.DecimalField(decimal_places=4, default=0.005, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
    ]
