# Generated by Django 5.1.6 on 2026-09-28 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0002_notificationlog_orderstatushistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_HUB', 'Arrived at Hub'), ('CLOSED', 'Closed')], default='CREATED', max_length=32)),
                ('origin', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location_name', models.CharField(blank=True, default='', max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_HUB', 'Arrived at Hub'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED_DELIVERY', 'Failed Delivery'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='CREATED', max_length=32)),
                ('carrier_name', models.CharField(blank=True, default='EcoExpress Carbon-Neutral', max_length=100)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_order_user_id',
            old_name='order_servi_user_id_c86839_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_order_status',
            old_name='order_servi_status_9e40f6_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_order_payment_status',
            old_name='order_servi_payment_f9eed4_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / Placed'), ('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('payment_confirmed', 'Payment Confirmed'), ('order_accepted', 'Order Accepted'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment Failed'), ('refunded', 'Refunded'), ('confirmed', 'Confirmed'), ('PENDING', 'Pending / Placed'), ('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('ORDER_ACCEPTED', 'Order Accepted'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded'), ('CONFIRMED', 'Confirmed')], default='ORDER_PLACED', max_length=40),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['status'], name='idx_container_status'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['destination'], name='idx_container_destination'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['last_location_update'], name='idx_container_last_loc_upd'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['container_code'], name='idx_container_code'),
        ),
        migrations.AddField(
            model_name='logisticstrackingevent',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='order_service.container'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='order_service.container'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='order_service.order'),
        ),
        migrations.AddField(
            model_name='logisticstrackingevent',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='order_service.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_allocations', to='order_service.orderitem'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_service.shipment'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order'], name='idx_shipment_order_id'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='idx_shipment_status'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['container'], name='idx_shipment_container_id'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='idx_shipment_track_num'),
        ),
        migrations.AddIndex(
            model_name='logisticstrackingevent',
            index=models.Index(fields=['shipment'], name='idx_tracking_shipment_id'),
        ),
        migrations.AddIndex(
            model_name='logisticstrackingevent',
            index=models.Index(fields=['container'], name='idx_tracking_container_id'),
        ),
        migrations.AddIndex(
            model_name='logisticstrackingevent',
            index=models.Index(fields=['timestamp'], name='idx_tracking_created_at'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['order_item'], name='idx_shp_item_ord_item_id'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['shipment'], name='idx_shp_item_shipment_id'),
        ),
    ]
