# Generated by Django 5.1.6 on 2026-10-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0005_orderitem_product_name_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('changed_by', models.CharField(blank=True, default='System', max_length=100)),
                ('changed_role', models.CharField(blank=True, default='Warehouse Staff', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='order_service.shipment')),
            ],
            options={
                'db_table': 'shipment_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['shipment'], name='idx_shpevt_shipment_id'), models.Index(fields=['created_at'], name='idx_shpevt_created_at')],
            },
        ),
    ]
