# Generated by Django 5.1.6 on 2026-10-02 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0006_shipmentevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryVerificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.BigIntegerField(blank=True, null=True)),
                ('verified_by', models.CharField(default='CUSTOMER_OTP', max_length=100)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('verification_method', models.CharField(default='CUSTOMER_OTP', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(blank=True, default='', max_length=50)),
                ('new_status', models.CharField(default='DELIVERED', max_length=50)),
                ('delivery_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('condition_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('RETURN_REQUESTED', 'Return Requested'), ('INSPECTION_REQUIRED', 'Inspection Required'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_REJECTED', 'Return Rejected'), ('RETURN_IN_TRANSIT', 'Return in Transit'), ('RETURN_RECEIVED', 'Return Received at Warehouse'), ('INSPECTION_PASSED', 'Inspection Passed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUND_PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refunded')], default='RETURN_REQUESTED', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('refund_id', models.CharField(blank=True, default='', max_length=100)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_by', models.CharField(blank=True, default='', max_length=100)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteExceptionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.BigIntegerField()),
                ('order_id', models.BigIntegerField()),
                ('actor_username', models.CharField(max_length=100)),
                ('actor_role', models.CharField(max_length=100)),
                ('expected_route', models.CharField(max_length=255)),
                ('actual_shipment_route', models.CharField(max_length=255)),
                ('exception_reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='idx_shipment_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='total_volume_m3',
            field=models.DecimalField(decimal_places=4, default=0.005, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='condition_required',
            field=models.TextField(blank=True, default='Unused, original packaging and tags intact'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_policy',
            field=models.TextField(blank=True, default='7-day replacement or return'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_window_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='volume_m3',
            field=models.DecimalField(decimal_places=4, default=0.005, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='max_volume_m3',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='max_weight_kg',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='used_volume_m3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='used_weight_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUND_PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / Placed'), ('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('payment_confirmed', 'Payment Confirmed'), ('order_accepted', 'Order Accepted'), ('processing', 'Processing'), ('packed', 'Packed'), ('ready_for_shipment', 'Ready for Shipment'), ('assigned_to_shipment', 'Assigned to Shipment'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivery_verification_started', 'Delivery Verification Started'), ('delivery_verified', 'Delivery Verified'), ('delivered', 'Delivered'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment Failed'), ('return_requested', 'Return Requested'), ('inspection_required', 'Inspection Required'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('return_in_transit', 'Return in Transit'), ('return_received', 'Return Received'), ('inspection_passed', 'Inspection Passed'), ('refund_pending', 'Refund Pending'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('confirmed', 'Confirmed'), ('PENDING', 'Pending / Placed'), ('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('ORDER_ACCEPTED', 'Order Accepted'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('READY_FOR_SHIPMENT', 'Ready for Shipment'), ('ASSIGNED_TO_SHIPMENT', 'Assigned to Shipment'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERY_VERIFICATION_STARTED', 'Delivery Verification Started'), ('DELIVERY_VERIFIED', 'Delivery Verified'), ('DELIVERED', 'Delivered'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCELLED', 'Cancelled'), ('PAYMENT_FAILED', 'Payment Failed'), ('RETURN_REQUESTED', 'Return Requested'), ('INSPECTION_REQUIRED', 'Inspection Required'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_REJECTED', 'Return Rejected'), ('RETURN_IN_TRANSIT', 'Return in Transit'), ('RETURN_RECEIVED', 'Return Received'), ('INSPECTION_PASSED', 'Inspection Passed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUND_PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refunded'), ('CONFIRMED', 'Confirmed')], default='ORDER_PLACED', max_length=40),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='order_service.order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open for Assignment'), ('FULL', 'Full'), ('READY_FOR_DISPATCH', 'Ready for Dispatch'), ('CREATED', 'Created'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_HUB', 'Arrived at Hub'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED_DELIVERY', 'Failed Delivery'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='OPEN', max_length=32),
        ),
        migrations.AddField(
            model_name='deliveryverificationaudit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_audits', to='order_service.order'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='order_service.order'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='order_service.orderitem'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='routeexceptionaudit',
            index=models.Index(fields=['shipment_id'], name='idx_route_exc_shp_id'),
        ),
        migrations.AddIndex(
            model_name='routeexceptionaudit',
            index=models.Index(fields=['order_id'], name='idx_route_exc_ord_id'),
        ),
        migrations.AddIndex(
            model_name='routeexceptionaudit',
            index=models.Index(fields=['timestamp'], name='idx_route_exc_time'),
        ),
        migrations.AddIndex(
            model_name='deliveryverificationaudit',
            index=models.Index(fields=['order'], name='idx_deliv_audit_ord_id'),
        ),
        migrations.AddIndex(
            model_name='deliveryverificationaudit',
            index=models.Index(fields=['shipment_id'], name='idx_deliv_audit_shp_id'),
        ),
        migrations.AddIndex(
            model_name='deliveryverificationaudit',
            index=models.Index(fields=['timestamp'], name='idx_deliv_audit_time'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['order'], name='idx_return_order_id'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['status'], name='idx_return_status'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['user'], name='idx_return_user_id'),
        ),
    ]
