# Generated by Django 5.1.6 on 2026-10-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0008_orderitem_variant_orderitem_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique customer-facing order number (ORD-YYYYMMDD-XXXX)', max_length=32, null=True, unique=True),
        ),
    ]
